package;

/**
 * ...
 * @author ninjaMuffin
 */
class Story 
{
	public static var story:Array<String> = 
	[
		"You wake",
		"You feel ill",
		"You do not remember a single thing",
		"Because you have died",
		"LOL RIP",
		"",
		"GAME OVER IDIOT",
		"", 
		"", 
		"",
		"jk lol",
		"You're good",
		"What you're about to play, is a video game",
		"My name is ninjamuffin99, I made this game",
		"This was a game created out of sorrow",
		"Out of sadness",
		"A game made out of pain",
		"You see, as of writing this, the steam winter sale is going on",
		"And as per usual I like to pick up a few",
		"indie games that I've heard about",
		"one such game I picked up yesterday was 'Cibele'",
		"by Nina Freeman and Star Maid Games",
		"I've heard some good and bad things about this game",
		"So I've decided to try the game myself",
		"And it was awful",
		"and I refunded it because I disliked it that much",
		"I tweeted my thoughts about the game, ",
		"so I won't go into detail here (so follow me @ninja_muffin99 ayyy)",
		"But it inspired me to make something better",
		"",
		"I'm making this game using only assets ",
		"I find for free on Itch.io or OpenGameArt.org",
		"This game is a mash of whatever stupid bullshit I find",
		"This game will be the best game you've ever played",
		"It will make you laugh",
		"You will cry",
		"And you will feel connected to the characters I present",
		"So I'd like to warn you right now",
		"You should be emotionally stable before playing this",
		"So if you're not doing alright...",
		"Feel free to exit the page and take care of yourself",
		"If you are in a crisis and considering suicide", 
		"call one of these various hotlines",
		"USA: 1-800-273-TALK (8255)",
		"UK:  08457 909090",
		"Germany:  0800-111 0 111 or 0800 - 111 0 333",
		"France: https://www.sos-amitie.com/",
		"Austrailia: 1300 22 4636",
		"Canada: http://suicideprevention.ca/thinking-about-suicide/find-a-crisis-centre/",
		"",
		"Italy: http://www.prevenireilsuicidio.it/",
		"New Zealand: 0800 543 354 ",
		"Finland: https://www.mll.fi/",
		"Alaska: lol fuk u guys lmaooooo",
		"Sometimes I forget about Alaska",
		"When I was like 3 or something I actually visited Alaska",
		"I don't remember it because Alaska sucks so much",
		"Maybe it's worse than Cibele ayyyy",
		"Ok I've been hard on both Cibele and Alaska",
		"They're alright, but I don't recommend experiencing either",
		"ACT I: THE BEGINNING",
		"10:54 AM",
		"You wake",
		"You see ur gf beside you.",
		"Hey baby, it's me ur gf",
		"Guess what day it is baby?",
		"It is your favorite holiday, Halloween!",
		"",
		"8 or so hours later",
		"",
		"Ok baby, I'll head to east street, and you can head to 5th Ave.!",
		"Be safe!",
		"You head down fifth avenue",
		"You head up to a house with some spooky decorations on it",
		"*knock knock nock*",
		"",
		"Aw yo that is a radical halloween costume my dude!",
		"You know what's more radical than your halloween costume??",
		"Drugs!",
		"I put some into your Snickers candy bar!",
		"But be safe with them! I do not be responsible for a death!",
		"I just wanna see the kids have some fun in a safe controlled environment!",
		"....",
		"JUST KIDDING FUCKER!!!",
		"YOU AREN'T GETTING MY TASTY DRUGS",
		"THIS SHIT COSTS MONEY BABY",
		"He slams the door",
		"You call ur gf",
		"Hey its me, ur gf!",
		"Yo, my pal was gonna head to a super cool halloween party and imma go!",
		"It's gonna be pretty rad yo, you should come along too",
		"you decide to come along too",
		"",
		"ACT II: THE PARTY",
		"You arrive at the party",
		"You walk inside",
		"you see ur gf",
		"hey baby!",
		"lets get some soda!",
		"Is this a dagger which I see before me, the handle toward my hand?",
		"Come, let me clutch thee.",
		"I have thee not, and yet I see thee still.",
		"Art thou not, fatal vision, sensible to feeling as to sight?",
		"Or art thou but A dagger of the mind, a false creation, Proceeding from the heat-oppressèd brain?",
		"I see thee yet, in form as palpable As this which now I draw.",
		"Thou marshall’st me the way that I was going, and such an instrument I was to use.",
		"Mine eyes are made the fools o' th' other senses, or else worth all the rest.",
		"I see thee still, and on thy blade and dudgeon gouts of blood, which was not so before.",
		"There’s no such thing.",
		"It is the bloody business which informs thus to mine eyes.",
		"Now o'er the one half-world nature seems dead, and wicked dreams abuse the curtained sleep.",
		"Witchcraft celebrates pale Hecate’s offerings,",
		"and withered murder, alarumed by his sentinel, the wolf",
		"Whose howl’s his watch, thus with his stealthy pace, with Tarquin’s ravishing strides, towards his design moves like a ghost.",
		"Thou sure and firm-set earth, hear not my steps, which way they walk, for fear thy very stones prate of my whereabout,",
		"And take the present horror from the time, which now suits with it",
		"Whiles I threat, he lives. Words to the heat of deeds too cold breath gives.",
		//A bell rings
		"I go, and it is done",
		"The bell invites me.",
		"Hear it not, Duncan, for it is a knell that summons thee to heaven or to hell.",
		//to be continued
		
		
	];

	public function new() 
	{
		
	}
	
}